[package]
name = "channel-myanmar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.12.4"
scraper = "0.19.0"
serde = { version = "1.0.203", features = ["derive"] }

[dev-dependencies]
tokio = { version = "1.38.0", features = ["full"] }
